language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"

install:
  - pip install cython

before_script:
  - mysql -e 'create database test_cymysql;'

script:
  - python setup.py test
  - python setup.py build_ext -i
  - python setup.py test
